name: release
on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Set RELEASE_VERSION ENV var
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Ensure container version is updated to release version
        run: |
          image=$(yq '.runs.image' action.yml)
          echo "Image: $image"
          imageVer=${image:(-6)}
          echo "Image version: $imageVer, Release version: ${{ env.RELEASE_VERSION }}"
          [[ "$imageVer" == "${{ env.RELEASE_VERSION }}" ]]
      
      - name: Install gox
        run: go install github.com/mitchellh/gox@v1.0.1

      - name: Build cross-platform binaries
        env:
          PLATFORMS: darwin/amd64 darwin/arm64 windows/amd64 linux/amd64 linux/arm64
          OUTPUT_PATH_FORMAT: ./bin/${{ env.RELEASE_VERSION }}/{{.OS}}/{{.Arch}}/go-test-coverage
        run: |
          gox -osarch="${PLATFORMS}" -ldflags "-X main.Version=${RELEASE_VERSION}" -output "${OUTPUT_PATH_FORMAT}"
      
      - name: Update the major version tag
        id: majorver
        uses: actions/publish-action@v0.1.0
        with:
          source-tag: ${{ env.RELEASE_VERSION }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            VERSION=${{ env.RELEASE_VERSION }}
          tags: |
            ghcr.io/vladopajic/go-test-coverage:${{ env.RELEASE_VERSION }}
            ghcr.io/vladopajic/go-test-coverage:${{ steps.majorver.outputs.major-tag }}
            ghcr.io/vladopajic/go-test-coverage:latest
